### ISSUE TITLE
Possible Sentry start-up race condition

### ISSUE THREAD

**Issue by zancarius** [zancarius/archlinux-pkgbuilds#10]
As per the discussion with @mitchhentges in PR #9 and IRC I'll be posting this issue in the event someone else encounters it before a reasonable solution is devised.

Essentially, the problem is thus: Rarely, during a cold start or following a reboot, it may be possible that enabling `sentry.service` isn't sufficient and when combined with nginx may prohibit nginx from communicating with Sentry. It appears that the only reliable workaround is to enable each of the dependent services individually (`sentry-celery`, `sentry-cron`, and `sentry-web`). We've had some difficulty recreating the problem consistently; it definitely _does_ occur, but I'm at a loss as to explain why or how.

Other possible solutions might be to set `max_fails=0`, `fail_timeout=0`, or configuring `slow_start` to a high-ish value (say, 30 seconds or more) in the `upstream` configuration when using nginx as a reverse proxy for Sentry. Try these first where possible, but do be aware of [their side effects](http://nginx.org/en/docs/http/ngx_http_upstream_module.html) and the implications of disabling this feature (some people are vehement about disabling it; others not so much).

At present, I haven't been able to replicate the problem. If anyone else is encountering this, please supply at a minimum the output of `systemd-analyze blame` and your system specs. It may also be helpful to supply an error log from nginx.

**Comment by zancarius** [comment]
I should note that I tested this recently on some old hardware. I have a rather antique laptop that still works and is probably of 2004-2005 vintage (x86-only, not 64-bit capable); that it functions is probably a factor of how much use it received (the disk has less than 2000 hours on it) and that it was relatively well cared for.

While I was able to set it up to run Sentry, I was *not* able to duplicate the problem cited in this issue. It certainly it takes more than a minute or two for Sentry and related services to settle, but I cannot actually force it to generate 5xx-level errors. One would assume that the dated nature of the hardware I used should have provoked it into failure. It didn't.

If I'm unable to come up with additional means of testing Sentry's startup with the configurations in this PKGBUILD, I will likely close this issue within another week or two if no one else reports it.

The relevant hardware I used in the hopes I could replicate this problem is, by memory, the following:

Intel Pentium M (~1.6GHz, single core; part of the original Centrino platform)
1.5GiB RAM

I may have access to even older hardware, but I'm not sure it's really worth my time trying to resurrect ancient systems in the hopes of maybe duplicating an issue that is unlikely to surface on more modern (and more common) hardware.

**Comment by mitchhentges** [comment]
Sounds good. It might even be due some weird state on my machine, and not necessarily anything sentry- or this package-related. Thanks for attempting to reproduce it, though :+1:

**Comment by zancarius** [comment]
Sure. I was excited for about 30 seconds when it appeared as though the issue may have been duplicated on this old laptop. And then it started working. This was probably one of the few times I've actually been disappointed something worked.

If you ever get a chance to try out some of the possible nginx workarounds we talked about previously (and in the initial ticket above), it would be interesting to see whether or not those have any effect. I'm not hopeful, but hey, you never know.

Hope you're having a great weekend. Cheers!

**Comment by zancarius** [comment]
Closing this issue as I've never been able to replicate it.
